version: '3.8'

# vector storage using pgvector on top of postgres
services:
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


