version: '3.8'

# vector storage using pgvector on top of postgres
services:
  app:
    build: .
    image: node:18
    ports:
      - 3000:3000
    volumes:
      - app_log:/app/logs
    # environment:
    #   - NODE_ENV=production

  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  app_log: