x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  restart: unless-stopped
  volumes:
    - ollama_data:/root/.ollama

# vector storage using pgvector on top of postgres
services:
  app:
    build: .
    image: node:18
    ports:
      - 3000:3000
    volumes:
      - app_log:/app/logs

  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  postgres_data:
  app_log:
  ollama_data:
